### PR TITLE
ESI::Base extended options and include_completed for industry

### PR DESCRIPTION
**Pull request by Mekaret**
Hi,

This pull request is based on #125 with the ESI::Base extented for supporting include_completed option.
If ok for you, I merge this PR with #125 .

The interested parts are https://github.com/biow0lf/eve_online/commit/725c8200d1eab2a4bdd053eb896c68ad090519c8 and https://github.com/biow0lf/eve_online/commit/a451b181bf4bdc3cbb9552f4aa2d6d85c9bed14e.

@+
Meka

### CODE REVIEW

**Comment by biow0lf** [comment]
Few notes:

1. Rename `lib/eve_online/esi/models/industry_jobs.rb` to `lib/eve_online/esi/models/industry_job.rb`. For consistency.

2. Rename `EveOnline::ESI::CorporationIndustryJob` to `EveOnline:: ESI::CorporationIndustryJobs` (with file)
3. Rename `EveOnline::ESI::CharacterIndustryJob` to `EveOnline::ESI:: CharacterIndustryJobs` (with file)

Rationale: Character has many jobs.

4. Remove:
```ruby
options.each do |k,v|
  instance_variable_set("@#{k}", v) unless v.nil?
end
```

As I see, this is unneeded this case.

5. `@include_completed = "false" if options[:include_completed].nil?` I think, this is not good, but ok for now. I will think about this later.

6. Extend examples:
```ruby
job.activity_id # => 5
job.blueprint_id # => 1024839597103
```
And so for all other fields in json.

7. Update CHANGELOG
8. Add yourself to Contributors section in README.md.

**Comment by biow0lf** [comment]
Ping

**Comment by Mekaret** [comment]
Pong ;-)

I was off this last days (business travel). I'll be working on it this week-end.

@+
Meka

**Comment by Mekaret** [comment]
Humm, if I delete this part of code 👍 
```ruby
options.each do |k,v|
  instance_variable_set("@#{k}", v) unless v.nil?
end
```
The variable don't seem to be initialized ;-(

```ruby
options = { corporation_id: 98146630, token: "1234", include_completed: "true" }
# => {:corporation_id=>98146630, :token=>"1234", :include_completed=>"true"}
corporation_jobs = EveOnline::ESI::CorporationIndustryJobs.new(options)
# => #<EveOnline::ESI::CorporationIndustryJobs:0x007fffece51de0 @corporation_id=98146630, @parser=JSON, @token="1234">
[4] pry(main)> corporation_jobs.url
# => "https://esi.tech.ccp.is/v1/corporations/98146630/industry/jobs/?datasource=tranquility&include_completed="

```

**Comment by biow0lf** [comment]
So, ok. I merged. I have few comments for this code, but I will write it in issues.

Also, welcome on a board. I add you as collaborator to this repo. Welcome! :)

**Pull request merged**
